# Generated by Django 4.0.3 on 2022-06-24 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_department_professor_answer_selection_question_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='qna.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ManyToManyField(related_name='department', to='qna.department'),
        ),
    ]
