# Generated by Django 4.0.3 on 2022-06-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_alter_major_department_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='qna.professor'),
        ),
    ]
