# Generated by Django 4.0.3 on 2022-06-24 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_alter_major_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.professor'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ManyToManyField(to='qna.department'),
        ),
    ]
