# Generated by Django 4.0.3 on 2022-06-25 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0005_alter_major_professor_alter_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='like',
        ),
        migrations.AddField(
            model_name='question',
            name='like_users',
            field=models.ManyToManyField(related_name='like_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
