# Generated by Django 4.0.3 on 2022-06-25 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0006_remove_question_like_question_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
