# Generated by Django 4.0.3 on 2022-07-07 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bookmark',
        ),
        migrations.AlterField(
            model_name='answer',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.profile'),
        ),
        migrations.AlterField(
            model_name='major',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.profile'),
        ),
    ]
