# Generated by Django 4.0.3 on 2022-07-08 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0013_remove_profile_bookmark_alter_answer_writer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_department', to='qna.department'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='qna.department'),
        ),
    ]
